Rerun System Tests on failure
We've seen that from time to time System Tests workflow fails due to problems
with connectivity to Electrum or due to some other randomly occurring issues
(like the problems with installing dependencies). We now add a job to the System
Tests workflow which is started only if one of the frevious jobs failed. The job
will trigger a Rerun workflow, which will then trigger the System Tests again.
The reason why we need to rerun via a separate workflow is because reruns cannot
be called on the workflows/jobs which are still running.

diff --git a/.github/workflows/system-tests.yml b/.github/workflows/system-tests.yml
--- a/.github/workflows/system-tests.yml
+++ b/.github/workflows/system-tests.yml
@@ -117,3 +117,30 @@ jobs:
           DEPOSITOR_BITCOIN_WIF: ${{ secrets.SYSTEM_TESTS_DEPOSITOR_PRIVATE_KEY_WIF }}
         run: |
           yarn test ./test/minting-unminting.test.ts --network $ETH_NETWORK
+
+  system-tests-trigger-rerun:
+    name: Trigger rerun of ${{ github.run_id }}
+    if: ${{ failure() }} # exeutes job if ancestor job have failed
+    needs: [system-tests-deposit-redemption, system-tests-minting-unminting]
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Trigger run of `Rerun` workflow"
+        shell: pwsh
+        env:
+          # GITHUB_TOKEN with actions: write will NOT work
+          # PAT Token must have workflow scope
+          RERUN_TOKEN: ${{ secrets.RERUN_TOKEN }}
+        run: |
+          echo "Running gh auth login..."
+          $env:RERUN_TOKEN | gh auth login --with-token
+          if(!$?) { exit 1 }
+          echo "Triggering rerun"
+          echo "
+          gh workflow run rerun.yml
+            --raw-field runId=$env:GITHUB_RUN_ID
+            --repo $env:GITHUB_REPOSITORY
+          "
+          gh workflow run rerun.yml `
+            --raw-field runId=$env:GITHUB_RUN_ID `
+            --repo $env:GITHUB_REPOSITORY
+          if(!$?) { exit 1 }
